const ACCOUNT_NAME = 'muzu_tan'
const AT_ACCOUNT_NAME = `@${ACCOUNT_NAME}`
const ACCOUNT_ID_STRING = '771649236'

const HANKAKU_OPTION_NUMBERS = ['1', '2', '3', '4']
const ZENKAKU_OPTION_NUMBERS = ['１', '２', '３', '４']
const OPTION_NUMBERS = [...HANKAKU_OPTION_NUMBERS, ...ZENKAKU_OPTION_NUMBERS]

module.exports = {
  ACCOUNT_NAME, AT_ACCOUNT_NAME, ACCOUNT_ID_STRING,
  HANKAKU_OPTION_NUMBERS, ZENKAKU_OPTION_NUMBERS, OPTION_NUMBERS,
}
