const ACCOUNT_NAME = 'muzu_tan'
const AT_ACCOUNT_NAME = `@${ACCOUNT_NAME}`

const HANKAKU_OPTION_NUMBERS = ['1', '2', '3', '4']
const ZENKAKU_OPTION_NUMBERS = ['１', '２', '３', '４']
const OPTION_NUMBERS = [...HANKAKU_OPTION_NUMBERS, ...ZENKAKU_OPTION_NUMBERS]

module.exports = {
  ACCOUNT_NAME, AT_ACCOUNT_NAME,
  HANKAKU_OPTION_NUMBERS, ZENKAKU_OPTION_NUMBERS, OPTION_NUMBERS,
}
